### ISSUE TITLE
Switching data product doesn't change clone title

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb-dashboard#123]
When opening a data product, on the right hand side there is a clone panel that allows you to clone this data product to another team. The top text box is prefilled with the name of the current data product.
When changing data products, this name remains the same. So if you start on data product 'foo', then change to data product 'bar', that text box will still say 'foo'. Refreshing the page does change the name 

The data product name that is prefilled in this box should change as you move to another data product.

**Comment by Francesca-Bit** [comment]
fixed in prod
