### ISSUE TITLE
cloning copies label of original rather than setting it

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb-dashboard#124]
When using the clone panel, you are given the option to set the database id of the destination. However, the label of the database will be set to whatever the original was, and there is no way to set this to something else.

This is especially annoying when cloning a database into the same team, as you just end up with the same data product name in the data product list with no indication that this actually a different data product.

I think it'd be more useful if the clone panel either alllowed you to set the label, or if the label just became the new data product name.

**Comment by Francesca-Bit** [comment]
We added a new feature. You can edit the database details, so after cloning you can edit the label and description
