### ISSUE TITLE
Document list triggers error in change request after a schema change

### ISSUE THREAD

**Issue by geoffwhittington** [terminusdb/terminusdb-dashboard#178]
I experience a "GraphQL query error" in a document list in the following case:

* Create a change request CR1 for an existing database
* Exit the change request CR1
* Make changes to a document schema and commit them
* Activate the change request CR1
* Open the document list for the modified document type

The error "GraphQL query error" is displayed. In the network pane the affected resource returns 404.

**Comment by Francesca-Bit** [comment]
fixed
