### ISSUE TITLE
View approved diffs works for new content only

### ISSUE THREAD

**Issue by geoffwhittington** [terminusdb/terminusdb-dashboard#192]
Upon viewing an approved change request, the user interface conveys the changes correctly for new content. When examining an approved request with changes to existing content, the diff does not show changes.

**Comment by GavinMendelGleason** [comment]
This was as designed to show between the point at which the merge took place. We could add another UI feature which compares with current main if that turns out to be useful.

**Comment by geoffwhittington** [comment]
Thank-you for clarifying the feature!
