### ISSUE TITLE
Unexpected message when previewing handlebars template

### ISSUE THREAD

**Issue by geoffwhittington** [terminusdb/terminusdb-dashboard#274]
When there exists no documents, the following message is produced:

![image](https://github.com/terminusdb/terminusdb-dashboard/assets/1770544/77efb68c-c0d4-4f4b-9dec-e62b4475b9c8)

Suggestion is to present a simplified message such as, `No documents found`

**Comment by Francesca-Bit** [comment]
We fixed the message
