### ISSUE TITLE
Overview report and document listing are in conflict

### ISSUE THREAD

**Issue by geoffwhittington** [terminusdb/terminusdb-dashboard#282]
In my instance, there are `6` documents for a type `Countermeasure`. However, in its listing there are none displayed:

![image](https://github.com/terminusdb/terminusdb-dashboard/assets/1770544/9a1ce362-ee9e-4f94-bda5-9544ffd75590)

NOTE: The image above combines screenshots of both views. Reach out if you'd like more details in order to investigate

**Comment by GavinMendelGleason** [comment]
We've determined the cause of this! We have a fix in dev and are getting ready to release it.

**Comment by Francesca-Bit** [comment]
this is fixed, please check in terminuscms
