### ISSUE TITLE
Unable to search documents after running vector index

### ISSUE THREAD

**Issue by geoffwhittington** [terminusdb/terminusdb-dashboard#283]
I'm unable to search documents after following the prescribed process for enabling vector search. After adding my OpenAI key, configuring the handlebar templates, and submitting a change request the expected vector index process executes.

![image](https://github.com/terminusdb/terminusdb-dashboard/assets/1770544/fca02bf0-4862-4868-a091-bd40640f4bcc)

When I open "search" (the magnifying glass under the openai logo) I see the message, "Get started with Indexing Actions
You need to index your data before you can search". This suggests that the setup is still incomplete.

The indexing seems to work, according to the API traffic:

![image](https://github.com/terminusdb/terminusdb-dashboard/assets/1770544/4e91f6f9-65c5-4d32-8c99-377d2901480b)

and looking at one of the index requests, it appears to be successful as well:

![image](https://github.com/terminusdb/terminusdb-dashboard/assets/1770544/5f0b640a-3a10-42a4-ab1a-81f71b8cd5bc)

When I preview the documents in the `openai_configuration` I get the following error for one of the types even though there should be documents of this type in the system:

![image](https://github.com/terminusdb/terminusdb-dashboard/assets/1770544/6d7158e4-7fbf-45b9-a24a-10493af5039e)

This search issue may be related to #282

**Comment by Francesca-Bit** [comment]
We fixed this
