### ISSUE TITLE
xdd:coordinate dashboard support for adding document

### ISSUE THREAD

**Issue by coutouly** [terminusdb/terminusdb-dashboard#73]
in the dashboard i try to add a document with a xdd:coordiate in the property.

`{
  "@key": {
    "@type": "ValueHash"
  },
  "@type": "Class",
  "ID": "xsd:string",
  "cp": "xsd:integer",
  "location": "xdd:coordinate",
  "numero": "xsd:string",
  "plan": "xsd:string",
  "rue": "xsd:string",
  "ville": "xsd:string"
}`

i get this error :

location*
Unsupported field schema for field root_location: Unknown field type undefined.

{
  "info": "DATA_TYPE",
  "title": "location"
}
![Capture d’écran_2022-12-05_16-52-30](https://user-images.githubusercontent.com/7043117/205681673-0072ee99-74da-495a-8ecd-4249bca42571.png)

**Comment by Francesca-Bit** [comment]
xdd:coordinate is deprecated, please use geojson https://github.com/terminusdb-labs/GeoJSON
